import 'bootstrap/dist/css/bootstrap.min.css';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';

import Footer from '../components/Footer';
import GoogleMap from '../components/Map';
import Head from 'next/head';
import Header from '../components/Header';
import React from 'react';
import ReadyBanner from '../components/ReadyBanner';
import SubHeader from '../components/SubHeader';

function AboutPage() {
	return (
		<div>
			<Head>
				<title>Res</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Header title='About Us' member='' members='' />
			<ReadyBanner />
			<GoogleMap />
			<Footer />
		</div>
	);
}

export default AboutPage;
